<div class="d-flex bd-highlight mb-3">
    <div class="me-auto p-2 bd-highlight"><h2>Customers</div>
    <div class="p-2 bd-highlight">
        <a class="btn btn-secondary btn-sm" href="<?=URL . 'customers'; ?>">Back</a>
    </div>
</div>


<form action="<?php echo URL; ?>customers/save" method="POST">
    <table class="table table-hover table-stripped">
        <tr>
            <td><label>Name</label></td>
            <td><input class="form-control" type="text" name="name" value="" required /></td>
        </tr>
        <tr>
            <td><label>E-mail</label></td>
            <td><input class="form-control" type="email" name="email" value="" required /></td>
        </tr>
        <tr>
            <td><label>Phone</label></td>
            <td><input class="form-control" type="tel" name="phone" value="" required /></td>
        </tr>
        <tr>
            <td><label>Bith Date</label></td>
            <td><input class="form-control" type="date" name="birth_date" value="" required /></td>
        </tr>

        <tr>
            <td colspan="2">
                <h3>
                    Addresses
                    <button type="button" class="btn btn-warning btn-sm float-end" id="duplicate">Add Address</button>
                </h3>
                
            </td>
        </tr>
    </table>


    <div id="duplicater">
        <table class="table table-hover table-stripped">
            <tr>
                <td colspan="2">Address</td>
            </tr>
            <tr>
                <td><label>Description</label></td>
                <td><input class="form-control" type="text" name="description[]" value="" required /></td>
            </tr>
            <tr>
                <td><label>Address</label></td>
                <td><input class="form-control" type="text" name="address[]" value="" required /></td>
            </tr>
            <tr>
                <td><label>Country</label></td>
                <td><input class="form-control" type="text" name="country[]" value="" required /></td>
            </tr>
            <tr>
                <td><label>State</label></td>
                <td><input class="form-control" type="text" name="state[]" value="" required /></td>
            </tr>
            <tr>
                <td><label>City</label></td>
                <td><input class="form-control" type="text" name="city[]" value="" required /></td>
            </tr>
            <tr>
                <td><label>zipcode</label></td>
                <td><input class="form-control" type="number" name="zipcode[]" value="" required /></td>
            </tr>
        </table>
    </div>

    <div id="duplicates">

    </div>


    <table>
        <tr>
            <td></td>
            <td><button type="submit" class="btn btn-primary btn-sm">Save</button></td>
        </tr>
    </table>
</form>