<div class="d-flex bd-highlight mb-3">
    <div class="me-auto p-2 bd-highlight"><h2>Customers</div>
    <div class="p-2 bd-highlight">
        <a class="btn btn-secondary btn-sm" href="<?=URL . 'customers'; ?>">Back</a>
    </div>
</div>


<form action="<?php echo URL; ?>customers/update/<?php echo html_escape($customer->id)?>" method="POST">
    <table class="table table-hover table-stripped">
        <tr>
            <td><label>Name</label></td>
            <td><input class="form-control" type="text" name="name" value="<?php echo html_escape($customer->name)?>" required /></td>
        </tr>
        <tr>
            <td><label>E-mail</label></td>
            <td><input class="form-control" type="email" name="email" value="<?php echo html_escape($customer->email)?>" required /></td>
        </tr>
        <tr>
            <td><label>Phone</label></td>
            <td><input class="form-control" type="tel" name="phone" value="<?php echo html_escape($customer->phone)?>" required /></td>
        </tr>
        <tr>
            <td><label>Bith Date</label></td>
            <td><input class="form-control" type="date" name="birth_date" value="<?php echo html_escape($customer->birth_date)?>" required /></td>
        </tr>

        <tr>
            <td colspan="2">
                <h3>
                    Addresses
                </h3>
            </td>
        </tr>
    </table>


    <div id="duplicater">
        <?php
        foreach ($addresses as $key => $addres) {
        ?>
        <table class="table table-hover table-stripped">
            <tr>
                <td colspan="2">Address <?=$key + 1?></td>
            </tr>
            <tr>
                <td><label>Description</label></td>
                <td><input class="form-control" type="text" name="description[]" value="<?php echo html_escape($addres->description)?>" required /></td>
            </tr>
            <tr>
                <td><label>Address</label></td>
                <td><input class="form-control" type="text" name="address[]" value="<?php echo html_escape($addres->address)?>" required /></td>
            </tr>
            <tr>
                <td><label>Country</label></td>
                <td><input class="form-control" type="text" name="country[]" value="<?php echo html_escape($addres->country)?>" required /></td>
            </tr>
            <tr>
                <td><label>State</label></td>
                <td><input class="form-control" type="text" name="state[]" value="<?php echo html_escape($addres->state)?>" required /></td>
            </tr>
            <tr>
                <td><label>City</label></td>
                <td><input class="form-control" type="text" name="city[]" value="<?php echo html_escape($addres->city)?>" required /></td>
            </tr>
            <tr>
                <td><label>zipcode</label></td>
                <td><input class="form-control" type="number" name="zipcode[]" value="<?php echo html_escape($addres->zipcode)?>" required /></td>
            </tr>
            <input type="hidden" name="address_id[]" value="<?php echo html_escape($addres->id)?>" />
        </table>
        <?php
        }
        ?>
    </div>


    <table>
        <tr>
            <td></td>
            <td><button type="submit" class="btn btn-primary btn-sm">Save</button></td>
        </tr>
    </table>
</form>
