<div class="d-flex bd-highlight mb-3">
    <div class="me-auto p-2 bd-highlight"><h2>Addresses</div>
    <div class="p-2 bd-highlight">
        <a class="btn btn-primary btn-sm" href="<?=URL . 'addreses/add'; ?>">Create</a>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-striped table-hover table-sm">
        <thead>
            <tr>
                <th scope="col">Description</th>
                <th scope="col">Address</th>
                <th scope="col">Country</th>
                <th scope="col">City</th>
                <th scope="col">State</th>
                <th scope="col">zipcode</th>
                <th scope="col">ACTIONS</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if($addresses) {
                foreach ($addresses as $address) {
            ?>
                    <tr>
                        <td><?php if (isset($address->description)) echo html_escape($address->description); ?></td>
                        <td><?php if (isset($address->address)) echo html_escape($address->address); ?></td>
                        <td><?php if (isset($address->country)) echo html_escape($address->country); ?></td>
                        <td><?php if (isset($address->state)) echo html_escape($address->state); ?></td>
                        <td><?php if (isset($address->city)) echo html_escape($address->city); ?></td>
                        <td><?php if (isset($address->zipcode)) echo html_escape($address->zipcode); ?></td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Actions">
                                <a class="btn btn-secondary btn-sm" href="<?php echo URL . 'addreses/edit/' . html_escape($address->id); ?>">edit</a>
                                <a class="btn btn-danger btn-sm" onclick="confirmDelete('<?=URL . 'addreses/delete/' . html_escape($address->id)?>')" href="javascript:void(0)">delete</a>
                            </div>
                        </td>
                    </tr>
            <?php 
                }
            } else {
                echo '<tr><td colspan="5">No addresses found</td></tr>';
            }
            ?>
        </tbody>
    </table>
</div>
<div class="text-left"><b>Total: <?php echo $total; ?></b></div>