
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><?=APP_TITTLE?></title>

    <link href="<?=asset('common/css/bootstrap.min.css')?>" rel="stylesheet" >

    <!-- Favicons -->
    <link rel="icon" href="<?=asset('img/favicons/favicon.ico')?>">
    <meta name="theme-color" content="#712cf9">

    <link href="<?=asset('common/css/dashboard.css')?>" rel="stylesheet">
    <?php isset($css) ? add_css($css) : ''; ?>
</head>
<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#"><?=APP_TITTLE?></a>
            <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
            <div class="navbar-nav">
                <div class="nav-item text-nowrap">
                    <a class="nav-link px-3" href="#">Sign out</a>
                </div>
            </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <?php require_once 'menu.phtml'; ?>

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 pt-4">
