<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="<?=URL?>">
                    <span data-feather="home" class="align-text-bottom"></span>
                    Dashboard
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo URL; ?>customers">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo URL; ?>addreses">Addresses</a>
            </li>          
        </ul>
    </div>
</nav>